### ISSUE TITLE
Add persistency for list of already analyzed posts

### ISSUE THREAD

**Issue by ktos** [ktos/Eleia#4]
At the moment list of already analyzed posts is only in memory and is lost after exit. Should be persisted somehow.

**Comment by AFM-Horizon** [comment]
Gday Ktos, I'm happy to have a look at this is you want.  Any preference for persistence technology?

**Comment by ktos** [comment]
Oh, that'd be great!

Actually, I don't care about technology that much, but I'd prefer something simple, don't use MSSQL ;)
