### ISSUE TITLE
Configureable ignoring

### ISSUE THREAD

**Issue by ktos** [ktos/Eleia#8]
At the moment we are ignoring everything which is not on "C#" subforum, but it should be configureable somehow.

Useful ids:

```
kariera 41
offtopic 7
flame 33
oceny 36
coyote 11
edukacja 40
```

**Comment by AFM-Horizon** [comment]
Hi man, I'm just looking into how this is implemented currently (hardcoded) is the idea that if the endpoint is in debug mode, that the ignore post functionality wont work?

**Comment by ktos** [comment]
Yeah - in Debug mode currently there is no ignoring of forum ids. But it could be, just never needed that :)
